# This file is used as dynamicconfig override for "activeactive" replication simulation scenario configured via host/testdata/replication_simulation_activeactive.yaml
system.writeVisibilityStoreName:
  - value: "db"
system.readVisibilityStoreName:
  - value: "db"
history.replicatorTaskBatchSize:
  - value: 25
    constraints: {}
frontend.failoverCoolDown:
  - value: 5s
history.ReplicationTaskProcessorStartWait: # default is 5s. repl task processor sleeps this much before processing received messages.
  - value: 10ms
history.standbyTaskMissingEventsResendDelay:
  - value: 5s
history.standbyTaskMissingEventsDiscardDelay:
  - value: 10s
history.standbyClusterDelay:
  - value: 10s
