// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/service.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorAPIYARPCClient is the YARPC client-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCClient interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest, ...yarpc.CallOption) (*GetShardOwnerResponse, error)
}

func newShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return &_ShardDistributorAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorAPIYARPCClient builds a new YARPC client for the ShardDistributorAPI service.
func NewShardDistributorAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorAPIYARPCClient {
	return newShardDistributorAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorAPIYARPCServer is the YARPC server-side interface for the ShardDistributorAPI service.
type ShardDistributorAPIYARPCServer interface {
	GetShardOwner(context.Context, *GetShardOwnerRequest) (*GetShardOwnerResponse, error)
}

type buildShardDistributorAPIYARPCProceduresParams struct {
	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorAPIYARPCProcedures(params buildShardDistributorAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "GetShardOwner",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.GetShardOwner,
							NewRequest:  newShardDistributorAPIServiceGetShardOwnerYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildShardDistributorAPIYARPCProcedures prepares an implementation of the ShardDistributorAPI service for YARPC registration.
func BuildShardDistributorAPIYARPCProcedures(server ShardDistributorAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorAPIYARPCClientParams defines the input
// for NewFxShardDistributorAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorAPIYARPCClient in an
// Fx application.
type FxShardDistributorAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorAPIYARPCClientResult defines the output
// of NewFxShardDistributorAPIYARPCClient. It provides a
// ShardDistributorAPIYARPCClient to an Fx application.
type FxShardDistributorAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorAPIYARPCClient provides a ShardDistributorAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorAPIYARPCClientParams) FxShardDistributorAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorAPIYARPCClientResult{
			Client: newShardDistributorAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorAPIYARPCProcedures. It provides
// ShardDistributorAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorAPIYARPCProcedures provides ShardDistributorAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorAPIYARPCProceduresParams) FxShardDistributorAPIYARPCProceduresResult {
		return FxShardDistributorAPIYARPCProceduresResult{
			Procedures: buildShardDistributorAPIYARPCProcedures(buildShardDistributorAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorAPIReflectionMeta,
		}
	}
}

// ShardDistributorAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorAPI",
	FileDescriptors: yarpcFileDescriptorClosure0055bfd59dff1f95,
}

type _ShardDistributorAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorAPIYARPCCaller) GetShardOwner(ctx context.Context, request *GetShardOwnerRequest, options ...yarpc.CallOption) (*GetShardOwnerResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "GetShardOwner", request, newShardDistributorAPIServiceGetShardOwnerYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetShardOwnerResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse, responseMessage)
	}
	return response, err
}

type _ShardDistributorAPIYARPCHandler struct {
	server ShardDistributorAPIYARPCServer
}

func (h *_ShardDistributorAPIYARPCHandler) GetShardOwner(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *GetShardOwnerRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*GetShardOwnerRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.GetShardOwner(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newShardDistributorAPIServiceGetShardOwnerYARPCRequest() proto.Message {
	return &GetShardOwnerRequest{}
}

func newShardDistributorAPIServiceGetShardOwnerYARPCResponse() proto.Message {
	return &GetShardOwnerResponse{}
}

var (
	emptyShardDistributorAPIServiceGetShardOwnerYARPCRequest  = &GetShardOwnerRequest{}
	emptyShardDistributorAPIServiceGetShardOwnerYARPCResponse = &GetShardOwnerResponse{}
)

var yarpcFileDescriptorClosure0055bfd59dff1f95 = [][]byte{
	// uber/cadence/sharddistributor/v1/service.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xcf, 0x4b, 0x02, 0x41,
		0x18, 0x65, 0x94, 0x42, 0xbf, 0x10, 0x62, 0xb2, 0x10, 0xeb, 0x20, 0x9e, 0x3c, 0xcd, 0xa2, 0x81,
		0x45, 0x9e, 0x8a, 0x2c, 0x44, 0xd2, 0xb2, 0x5b, 0x97, 0x98, 0xdd, 0xfd, 0xd0, 0xa5, 0x9c, 0xb1,
		0xf9, 0xb1, 0xe1, 0xad, 0x3f, 0xa3, 0xff, 0xb1, 0x7f, 0x22, 0x76, 0xd4, 0x64, 0x17, 0x29, 0xec,
		0xb6, 0xf3, 0xbe, 0xb7, 0x6f, 0xde, 0xf7, 0xe6, 0x01, 0xb3, 0x3e, 0x2a, 0x2f, 0xe0, 0x21, 0x8a,
		0x00, 0x3d, 0x3d, 0xe1, 0x2a, 0x0c, 0x23, 0x6d, 0x54, 0xe4, 0x5b, 0x23, 0x95, 0x17, 0x37, 0x3d,
		0x8d, 0x2a, 0x8e, 0x02, 0x64, 0x33, 0x25, 0x8d, 0xa4, 0xb5, 0x84, 0xcf, 0x96, 0x7c, 0x96, 0xe5,
		0xb3, 0xb8, 0x59, 0x7f, 0x80, 0xf2, 0x2d, 0x9a, 0xc7, 0x64, 0x32, 0x7c, 0x17, 0xa8, 0x46, 0xf8,
		0x66, 0x51, 0x1b, 0x7a, 0x0c, 0x45, 0x47, 0x7f, 0x7e, 0xc1, 0x79, 0x85, 0xd4, 0x48, 0xa3, 0x38,
		0x2a, 0x38, 0xa0, 0x8f, 0x73, 0x7a, 0x02, 0x45, 0xc1, 0xa7, 0xa8, 0x67, 0x3c, 0xc0, 0x4a, 0xce,
		0x0d, 0xd7, 0x40, 0xfd, 0x8b, 0xc0, 0x61, 0x46, 0x53, 0xcf, 0xa4, 0xd0, 0x48, 0xcb, 0xb0, 0x23,
		0x13, 0x60, 0x29, 0xb8, 0x38, 0xfc, 0xae, 0x46, 0x39, 0x14, 0xa6, 0x68, 0x78, 0xc8, 0x0d, 0xaf,
		0xe4, 0x6b, 0xf9, 0xc6, 0x5e, 0xab, 0xcb, 0xfe, 0xda, 0x8a, 0x6d, 0xbc, 0x9e, 0xdd, 0x2d, 0x75,
		0xba, 0xc2, 0xa8, 0xf9, 0xe8, 0x47, 0xb6, 0xda, 0x81, 0x52, 0x6a, 0x44, 0xf7, 0x21, 0xbf, 0x5e,
		0x3b, 0xf9, 0x4c, 0x9c, 0xc7, 0xfc, 0xd5, 0xae, 0xfc, 0x2d, 0x0e, 0x17, 0xb9, 0x73, 0x52, 0x6f,
		0xc3, 0xd1, 0x60, 0x65, 0x76, 0x20, 0xcd, 0x8d, 0xb4, 0x22, 0xec, 0x2a, 0x25, 0x33, 0x7b, 0x91,
		0x6c, 0x4a, 0x43, 0xa0, 0xce, 0xe2, 0x16, 0xff, 0xa4, 0x1f, 0x25, 0x97, 0x7e, 0x94, 0xd6, 0x27,
		0x81, 0x03, 0xa7, 0x78, 0xbd, 0xce, 0xe2, 0xf2, 0xbe, 0x47, 0x3f, 0x08, 0x94, 0x52, 0x79, 0xd0,
		0xf6, 0xd6, 0x01, 0xba, 0x4e, 0x54, 0xcf, 0xfe, 0x19, 0xfc, 0x55, 0xff, 0xa9, 0x37, 0x8e, 0xcc,
		0xc4, 0xfa, 0x2c, 0x90, 0x53, 0x2f, 0xd5, 0x61, 0x36, 0x46, 0xe1, 0xb9, 0xb2, 0x6e, 0xaa, 0x73,
		0x27, 0x8b, 0xc5, 0x4d, 0x7f, 0xd7, 0xb1, 0x4f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x12, 0x15,
		0x48, 0x60, 0x0c, 0x03, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorAPIYARPCClient {
			return NewShardDistributorAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
